#!/bin/bash

# Script de configuração para Railway - Ana Cardoso Bot v2
set -e

echo "🚀 Configurando projeto Railway para Ana Cardoso Bot..."
echo "📍 Projeto: ana-cardoso-bot-v2"
echo "🌐 GitHub: https://github.com/OctaDigital01/ana-cardoso-bot"
echo "🚂 Railway: https://railway.com/project/2e7a4879-f9a3-40d7-89b6-4339e3c5e6ac"
echo ""

# NOVO PROJETO IDs - Será necessário atualizar após criar os serviços
PROJECT_ID="2e7a4879-f9a3-40d7-89b6-4339e3c5e6ac"

echo "🔧 INSTRUÇÕES PARA CONFIGURAÇÃO MANUAL NO RAILWAY:"
echo ""
echo "1. Acesse o projeto Railway:"
echo "   https://railway.com/project/2e7a4879-f9a3-40d7-89b6-4339e3c5e6ac"
echo ""
echo "2. Adicione os seguintes serviços clicando em '+ New':"
echo "   a) PostgreSQL Database"
echo "   b) Redis Database"
echo "   c) Backend Service (conectar ao GitHub repo: backend folder)"
echo "   d) Frontend Service (conectar ao GitHub repo: frontend folder)"
echo ""
echo "3. Configurar variáveis de ambiente:"
echo ""

echo "📊 POSTGRESQL VARIABLES:"
echo "   POSTGRES_DB=telegram_bot_saas"
echo "   POSTGRES_USER=postgres" 
echo "   POSTGRES_PASSWORD=TelegramBotSaas2024_"
echo "   PGDATA=/var/lib/postgresql/data/pgdata"
echo ""

echo "🗄️ REDIS VARIABLES:"
echo "   REDIS_PASSWORD=TelegramBotRedis2024_"
echo ""

echo "⚡ BACKEND SERVICE VARIABLES:"
echo "   NODE_ENV=production"
echo "   PORT=3333"
echo "   DATABASE_URL=\${{Postgres.DATABASE_URL}}"
echo "   REDIS_URL=\${{Redis.REDIS_URL}}"
echo "   JWT_SECRET=telegram-bot-manager-super-secret-jwt-key-production-32-chars"
echo "   JWT_REFRESH_SECRET=telegram-bot-manager-super-secret-refresh-key-production-32-chars"
echo "   ENCRYPTION_KEY=telegrambotmanager32charkey12345"
echo "   TELEGRAM_WEBHOOK_DOMAIN=\${{RAILWAY_STATIC_URL}}"
echo "   FRONTEND_URL=[FRONTEND_SERVICE_URL]"
echo "   RATE_LIMIT_WINDOW=60000"
echo "   RATE_LIMIT_MAX=1000"
echo "   LOG_LEVEL=info"
echo "   ENABLE_REGISTRATION=true"
echo "   ENABLE_SWAGGER=false"
echo ""

echo "🎨 FRONTEND SERVICE VARIABLES:"
echo "   NODE_ENV=production"
echo "   PORT=3000"
echo "   NEXT_PUBLIC_API_URL=\${{Backend.RAILWAY_STATIC_URL}}/api/v1"
echo "   NEXT_PUBLIC_WS_URL=wss://\${{Backend.RAILWAY_STATIC_URL}}"
echo "   NEXT_PUBLIC_APP_URL=\${{RAILWAY_STATIC_URL}}"
echo "   NEXT_PUBLIC_APP_NAME=Ana Cardoso Bot Manager"
echo "   NEXT_PUBLIC_ENABLE_PWA=true"
echo "   NEXT_PUBLIC_ENABLE_ANALYTICS=true"
echo "   NEXT_TELEMETRY_DISABLED=1"

echo ""
echo "4. CONFIGURAÇÃO DOS SERVIÇOS:"
echo ""
echo "   Para BACKEND SERVICE:"
echo "   - Root Directory: /backend"
echo "   - Build Command: npm run build"  
echo "   - Start Command: node dist/server.js"
echo ""
echo "   Para FRONTEND SERVICE:"
echo "   - Root Directory: /frontend"
echo "   - Build Command: npm run build"
echo "   - Start Command: npm start"
echo ""

echo "5. APÓS CONFIGURAR TUDO:"
echo "   - Deploy todos os serviços"
echo "   - Configurar domínios customizados se necessário"
echo "   - Testar as URLs geradas"
echo ""

echo "📋 CHECKLIST DE DEPLOYMENT:"
echo "   □ PostgreSQL adicionado e rodando"
echo "   □ Redis adicionado e rodando"  
echo "   □ Backend conectado ao GitHub e rodando"
echo "   □ Frontend conectado ao GitHub e rodando"
echo "   □ Todas as variáveis configuradas"
echo "   □ URLs funcionando corretamente"
echo ""

echo "🎯 IMPORTANTE:"
echo "   - Substitua [FRONTEND_SERVICE_URL] pela URL real do frontend após deploy"
echo "   - Configure seu TELEGRAM_BOT_TOKEN nas variáveis do backend"
echo "   - Use \${{SERVICE_NAME.VARIABLE}} para referências entre serviços"
echo ""

echo "🎉 Configuração preparada!"
echo "📊 Dashboard: https://railway.com/project/$PROJECT_ID"
echo "🌐 GitHub: https://github.com/OctaDigital01/ana-cardoso-bot"