# Nixpacks configuration for Railway
[build]
  cmd = "npm run build"

[start]
  cmd = "npm start"

[phases.setup]
  nixPkgs = ["nodejs", "npm"]

[phases.install]
  cmd = "npm ci --production=false"

[phases.build]
  cmd = "npm run build"

[variables]
  NODE_ENV = "production"