# Railway Configuration
[build]
  builder = "DOCKERFILE"
  dockerfilePath = "Dockerfile"

[deploy]
  numReplicas = 1
  sleepApplication = false
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 3

# Backend Service
[[services]]
  name = "backend"
  source = "backend"
  
  [services.build]
    builder = "DOCKERFILE"
    dockerfilePath = "Dockerfile"
  
  [services.deploy]
    startCommand = "node dist/server.js"
    healthcheckPath = "/health"
    healthcheckTimeout = 300
    numReplicas = 1
    
  [[services.variables]]
    name = "NODE_ENV"
    value = "production"
    
  [[services.variables]]
    name = "PORT"
    value = "3333"

# Frontend Service
[[services]]
  name = "frontend"
  source = "frontend"
  
  [services.build]
    builder = "DOCKERFILE"
    dockerfilePath = "Dockerfile"
    
  [services.deploy]
    startCommand = "node server.js"
    healthcheckPath = "/"
    healthcheckTimeout = 300
    numReplicas = 1
    
  [[services.variables]]
    name = "NODE_ENV" 
    value = "production"
    
  [[services.variables]]
    name = "PORT"
    value = "3000"

# Database Service
[[services]]
  name = "postgres"
  
  [services.deploy]
    template = "postgresql"
    
# Redis Service  
[[services]]
  name = "redis"
  
  [services.deploy]
    template = "redis"