[build]
  builder = "nixpacks"

[deploy]
  startCommand = "echo 'Multiple services - see individual service configuration'"
  restartPolicyType = "never"

# Backend service configuration
[[services]]
  name = "backend"
  rootDirectory = "backend"
  
  [services.build]
    command = "npm run build"
  
  [services.deploy]
    startCommand = "node dist/server.js"
    
  [services.variables]
    NODE_ENV = "production"
    PORT = "3333"

# Frontend service configuration  
[[services]]
  name = "frontend"
  rootDirectory = "frontend"
  
  [services.build]
    command = "npm run build"
    
  [services.deploy]
    startCommand = "npm start"
    
  [services.variables]
    NODE_ENV = "production"
    PORT = "3000"