[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "backend"
source = "backend"

[services.build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[services.deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[services.variables]
NODE_ENV = "production"
PORT = "3333"
DATABASE_URL = "postgresql://postgres:password@postgres:5432/telegram_bot_saas"
JWT_SECRET = "your-super-secret-jwt-key-change-in-production"
TELEGRAM_BOT_TOKEN = "your-telegram-bot-token-here"
REDIS_URL = "redis://redis:6379"
STRIPE_SECRET_KEY = "your-stripe-secret-key"
STRIPE_WEBHOOK_SECRET = "your-stripe-webhook-secret"

[[services]]
name = "frontend" 
source = "frontend"

[services.build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[services.deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[services.variables]
NODE_ENV = "production"
NEXT_PUBLIC_API_URL = "https://backend.railway.app"
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "your-stripe-publishable-key"

[[services]]
name = "postgres"
source = "postgres:15"

[services.variables]
POSTGRES_DB = "telegram_bot_saas"
POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = "password"

[[services]]
name = "redis"
source = "redis:alpine"
