[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm', 'python3']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npm run build', 'npx prisma generate']

[start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production'
PORT = '3333'